-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Pacote"
(
    codigo serial NOT NULL,
    valor double precision,
    data_ini date,
    data_fim date,
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public."Visita"
(
    codigo serial NOT NULL,
    nome character varying(63),
    endereco character varying(127),
    datahora_ini timestamp without time zone,
    datahora_fim timestamp without time zone,
    tipo_visita integer,
    codigo_cidade integer,
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public."Cidade"
(
    codigo serial NOT NULL,
    nome character varying(63),
    estado character varying(63),
    populacao integer,
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public."Hotel"
(
    categoria character varying(63),
    codigo_visita integer
);

CREATE TABLE IF NOT EXISTS public."Restaurante"
(
    especialidade character varying(63),
    preco_medio double precision,
    categoria character varying(63),
    codigo_visita integer,
    hotel_associado integer,
    casa_de_show_associada integer
);

CREATE TABLE IF NOT EXISTS public."Quarto"
(
    codigo serial NOT NULL,
    nome character varying(63),
    valor double precision,
    tipo character varying(63),
    codigo_hotel integer,
    PRIMARY KEY (codigo_hotel)
);

CREATE TABLE IF NOT EXISTS public."Casa de Show"
(
    hora_ini time without time zone,
    hora_fim time without time zone,
    dia_fecha character varying(15),
    codigo_pontoturistico integer
);

CREATE TABLE IF NOT EXISTS public."Ponto Turistico"
(
    codigo serial NOT NULL,
    "desc" character varying(63),
    codigo_visita integer,
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public."Museu"
(
    data_funda date,
    n_salas integer,
    codigo_pontoturistico integer,
    codigo_fundador integer
);

CREATE TABLE IF NOT EXISTS public."Fundador"
(
    codigo serial NOT NULL,
    nome character varying(127),
    data_nasc date,
    data_obito date,
    trabalho character varying(63),
    nacionalidade character varying(63),
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public."Igreja"
(
    data_const date,
    estilo character varying(63),
    codigo_pontoturistico integer
);

CREATE TABLE IF NOT EXISTS public."Cliente"
(
    codigo serial NOT NULL,
    nome character varying(127),
    endereco character varying(127),
    fone character varying(15),
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public."Pessoa Fisica"
(
    cpf character varying(15) NOT NULL,
    codigo_cliente integer,
    PRIMARY KEY (cpf)
);

CREATE TABLE IF NOT EXISTS public."Pessoa Juridica"
(
    cnpj character varying(31) NOT NULL,
    codigo_cliente integer,
    PRIMARY KEY (cnpj)
);

CREATE TABLE IF NOT EXISTS public."Tipo Visita"
(
    codigo serial NOT NULL,
    nome character varying(63),
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public."Cliente_Pacote"
(
    "Cliente_codigo" serial NOT NULL,
    "Pacote_codigo" serial NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Pacote_Visita"
(
    "Pacote_codigo" serial NOT NULL,
    "Visita_codigo" serial NOT NULL
);

ALTER TABLE IF EXISTS public."Visita"
    ADD FOREIGN KEY (tipo_visita)
    REFERENCES public."Tipo Visita" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Visita"
    ADD FOREIGN KEY (codigo_cidade)
    REFERENCES public."Cidade" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Hotel"
    ADD FOREIGN KEY (codigo_visita)
    REFERENCES public."Visita" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Restaurante"
    ADD FOREIGN KEY (codigo_visita)
    REFERENCES public."Visita" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Restaurante"
    ADD FOREIGN KEY (hotel_associado)
    REFERENCES public."Hotel" (codigo_visita) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Restaurante"
    ADD FOREIGN KEY (casa_de_show_associada)
    REFERENCES public."Casa de Show" (codigo_pontoturistico) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Quarto"
    ADD FOREIGN KEY (codigo_hotel)
    REFERENCES public."Hotel" (codigo_visita) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Casa de Show"
    ADD FOREIGN KEY (codigo_pontoturistico)
    REFERENCES public."Ponto Turistico" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Ponto Turistico"
    ADD FOREIGN KEY (codigo_visita)
    REFERENCES public."Visita" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Museu"
    ADD FOREIGN KEY (codigo_pontoturistico)
    REFERENCES public."Ponto Turistico" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Museu"
    ADD FOREIGN KEY (codigo_fundador)
    REFERENCES public."Fundador" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Igreja"
    ADD FOREIGN KEY (codigo_pontoturistico)
    REFERENCES public."Ponto Turistico" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pessoa Fisica"
    ADD FOREIGN KEY (codigo_cliente)
    REFERENCES public."Cliente" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pessoa Juridica"
    ADD FOREIGN KEY (codigo_cliente)
    REFERENCES public."Cliente" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Cliente_Pacote"
    ADD FOREIGN KEY ("Pacote_codigo")
    REFERENCES public."Pacote" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Cliente_Pacote"
    ADD FOREIGN KEY ("Cliente_codigo")
    REFERENCES public."Cliente" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pacote_Visita"
    ADD FOREIGN KEY ("Pacote_codigo")
    REFERENCES public."Pacote" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pacote_Visita"
    ADD FOREIGN KEY ("Visita_codigo")
    REFERENCES public."Visita" (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;