
package sdi.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IFornecedor", targetNamespace = "http://sdi/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IFornecedor {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://sdi/IFornecedor/pagarRequest", output = "http://sdi/IFornecedor/pagarResponse")
    public boolean pagar(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ComprarProdutos")
    @WebResult(partName = "return")
    @Action(input = "http://sdi/IFornecedor/ComprarProdutosRequest", output = "http://sdi/IFornecedor/ComprarProdutosResponse")
    public double comprarProdutos(
        @WebParam(name = "arg0", partName = "arg0")
        StringArray arg0);

}
