
package sdi.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerFornecedorImplService", targetNamespace = "http://sdi/", wsdlLocation = "http://127.0.0.1:9876/WSFornecedor?wsdl")
public class ServerFornecedorImplService
    extends Service
{

    private final static URL SERVERFORNECEDORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERFORNECEDORIMPLSERVICE_EXCEPTION;
    private final static QName SERVERFORNECEDORIMPLSERVICE_QNAME = new QName("http://sdi/", "ServerFornecedorImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9876/WSFornecedor?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERFORNECEDORIMPLSERVICE_WSDL_LOCATION = url;
        SERVERFORNECEDORIMPLSERVICE_EXCEPTION = e;
    }

    public ServerFornecedorImplService() {
        super(__getWsdlLocation(), SERVERFORNECEDORIMPLSERVICE_QNAME);
    }

    public ServerFornecedorImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERFORNECEDORIMPLSERVICE_QNAME, features);
    }

    public ServerFornecedorImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVERFORNECEDORIMPLSERVICE_QNAME);
    }

    public ServerFornecedorImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERFORNECEDORIMPLSERVICE_QNAME, features);
    }

    public ServerFornecedorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerFornecedorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IFornecedor
     */
    @WebEndpoint(name = "ServerFornecedorImplPort")
    public IFornecedor getServerFornecedorImplPort() {
        return super.getPort(new QName("http://sdi/", "ServerFornecedorImplPort"), IFornecedor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFornecedor
     */
    @WebEndpoint(name = "ServerFornecedorImplPort")
    public IFornecedor getServerFornecedorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sdi/", "ServerFornecedorImplPort"), IFornecedor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERFORNECEDORIMPLSERVICE_EXCEPTION!= null) {
            throw SERVERFORNECEDORIMPLSERVICE_EXCEPTION;
        }
        return SERVERFORNECEDORIMPLSERVICE_WSDL_LOCATION;
    }

}
